### ISSUE TITLE
browse works but always opens new page with 10 pathways when clicking next

### ISSUE THREAD

**Issue by mkutmon** [mkutmon/wikipathways-upgrade-UM#25]
Additional pathways are not loaded underneath each other but a new page is opened with the 10 next pathways.

**Comment by fehrhart** [comment]
And... clicking on one of the pathways (one of the first 10 of browse function) produces this error:

Internal error

[4097ae53a14d2277e4352aa2] /Pathway:WP2516 MWException from line 154 of /home/manager/wikipathways-upgrade-2017/extensions/GPMLConverter/src/Converter.php: Unable to convert to /home/manager/wikipathways-upgrade-2017/mediawiki/images/wikipathways/2/2b/WP2516_90247.pvjssvg:

Status: 1

Message:

Command: gpml2 --id 'WP2516' --pathway-version '90247' /home/manager/wikipathways-upgrade-2017/mediawiki/images/wikipathways/2/2b/WP2516_90247.gpml /home/manager/wikipathways-upgrade-2017/mediawiki/images/wikipathways/2/2b/WP2516_90247.pvjssvg

Backtrace:

#0 /home/manager/wikipathways-upgrade-2017/extensions/WikiPathways/src/PathwayCache/Convertible.php(71): WikiPathways\GPML\Converter::convert(string, string, array)
#1 /home/manager/wikipathways-upgrade-2017/extensions/WikiPathways/src/PathwayCache/Convertible.php(40): WikiPathways\PathwayCache\Convertible->convert(string, string)
#2 /home/manager/wikipathways-upgrade-2017/extensions/WikiPathways/src/PathwayCache/Base.php(73): WikiPathways\PathwayCache\Convertible->doRender()
#3 /home/manager/wikipathways-upgrade-2017/extensions/WikiPathways/src/PathwayCache/Base.php(83): WikiPathways\PathwayCache\Base->render()
#4 /home/manager/wikipathways-upgrade-2017/extensions/GPML/src/Content.php(329): WikiPathways\PathwayCache\Base->isCached()
#5 /home/manager/wikipathways-upgrade-2017/extensions/GPML/src/Content.php(273): WikiPathways\GPML\Content->renderDiagram()
#6 /home/manager/wikipathways-upgrade-2017/extensions/GPML/src/Content.php(263): WikiPathways\GPML\Content->getSections()
#7 /home/manager/wikipathways-upgrade-2017/extensions/GPML/src/Content.php(242): WikiPathways\GPML\Content->getHtml()
#8 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/content/AbstractContent.php(516): WikiPathways\GPML\Content->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#9 /home/manager/wikipathways-upgrade-2017/extensions/GPML/src/Content.php(206): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#10 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/poolcounter/PoolWorkArticleView.php(144): WikiPathways\GPML\Content->getParserOutput(Title, integer, ParserOptions)
#11 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#12 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/page/Article.php(604): PoolCounterWork->execute()
#13 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/actions/ViewAction.php(68): Article->view()
#14 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/MediaWiki.php(500): ViewAction->show()
#15 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/MediaWiki.php(294): MediaWiki->performAction(Article, Title)
#16 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/MediaWiki.php(861): MediaWiki->performRequest()
#17 /home/manager/wikipathways-upgrade-2017/mediawiki/includes/MediaWiki.php(524): MediaWiki->main()
#18 /home/manager/wikipathways-upgrade-2017/mediawiki/index.php(42): MediaWiki->run()
#19 {main}

**Comment by mkutmon** [comment]
@fehrhart that works for me - actually not completely true - the page loads but not properly!
http://137.120.17.147/Pathway:WP2516

Do you see this error for all pathways?

**Comment by mkutmon** [comment]
![image](https://user-images.githubusercontent.com/2158343/55807011-b9089680-5ae1-11e9-9dcb-387e1112e725.png)

**Comment by fehrhart** [comment]
Checking again on my home PC, it works now!
